version: "3.7"
services:
  db:
    image: mysql:5.7.37
    volumes:
      - data-mysql:/var/lib/mysql
      - ./sql/codepush-all.sql:/docker-entrypoint-initdb.d/codepush-all.sql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "On"
    networks:
      - dbnet
      
  redis:
    image: redis:6.2.5-alpine
    environment:
      REDIS_URL: redis://redis:6379
      ALLOW_EMPTY_PASSWORD: 1
    ports:
      - "6379:6379"
    networks:
      - redisnet

  server:
      build:
        target: dev
      command: ./node_modules/.bin/tsnd --rs --poll --respawn src/server.ts
      volumes:
        - ./src:/usr/src
        - ./sql:/usr/sql
        - ./package.json:/usr/package.json
        - ./tsconfig.json:/usr/tsconfig.json
      ports:
        - "5000:5000"
      environment:
        DB_HOST: "db"
        REDIS_URL: "redis://redis:6379"
      depends_on:
        - redis
        - db
      networks:
        - servernet
        - dbnet
        - redisnet


networks:
  servernet:
  dbnet:
  redisnet:

volumes:
  data-storage:
  data-tmp:
  data-mysql:
  data-redis:
